config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions, shallow: true do
    resources :answers, except: %i[show index]
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def author_of?(item)
    item.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    current_user.answers << @answer
    if @answer.save
      redirect_to question_path(@question), notice: 'Your answer successfully created.'
    else
      render 'questions/show'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    if current_user.author_of?(@answer)
      @answer.destroy
      redirect_to @answer.question, notice: 'Answer is successfully deleted.'
    else
      redirect_to @answer.question, notice: 'You are not an author'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question is successfully deleted.'
    else
      redirect_to @question, notice: 'You are not an author'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  p= answer.body

  div
    -if current_user&.author_of?(answer)
      =link_to 'Delete answer', answer_path(answer), method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question
= form_with model: @question, local: true do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/_question.html.slim
div
  h3= question.title
  p= question.body

app/views/questions/index.html.slim
p = link_to 'Ask question', new_question_path

div Questions:
= render @questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
div
  -if current_user&.author_of?(@question)
    = link_to "Delete question",
      question_path(@question),
      method: "delete"

div
  h1= @question.title
  p= @question.body

div
  h2 Answers:

div
  = render @question.answers

div
  h2 Enter your answer:
  = render 'shared/errors', resource: @answer
  = form_with model: [@question, @answer], local: true do |f|
    = f.label :body
    = f.text_area :body
    = f.submit 'Send Answer'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
-if user_signed_in?
  div
    p= current_user.email
    p= button_to('Log out', destroy_user_session_path, method: :delete)